version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: HotelBooking.Web/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=HotelBooking;User=root;Password=hotel123;
    depends_on:
      - db
    volumes:
      - ~/.aspnet/https:/https:ro

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: hotel123
      MYSQL_DATABASE: HotelBooking
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data: